#!/usr/bin/env node
// Build-time widget compiler: inlines the ext-apps bundle + logo SVGs into
// the carousel HTML and emits a single TS constant. Avoids runtime fs reads,
// which keeps the Vercel function hermetic.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const require = createRequire(import.meta.url);

// ext-apps browser bundle → inline as `globalThis.ExtApps = {...}`
const bundleRaw = readFileSync(
  require.resolve("@modelcontextprotocol/ext-apps/app-with-deps"),
  "utf8",
);
const bundleInline = bundleRaw.replace(
  /export\{([^}]+)\};?\s*$/,
  (_, body) =>
    "globalThis.ExtApps={" +
    body
      .split(",")
      .map((pair) => {
        const [local, exported] = pair.split(" as ").map((s) => s.trim());
        return `${exported ?? local}:${local}`;
      })
      .join(",") +
    "};",
);

// Amazon logo (light + dark)
const logoSvg = readFileSync(
  join(root, "widgets", "assets", "amazon-logo.svg"),
  "utf8",
);
const toDataSvg = (svg) =>
  "data:image/svg+xml;base64," + Buffer.from(svg, "utf8").toString("base64");
const logoLight = toDataSvg(logoSvg);
const logoDark = toDataSvg(logoSvg.replace(/#221f1f/gi, "#ffffff"));

// Compose
const html = readFileSync(join(root, "widgets", "amazon-carousel.html"), "utf8")
  .replace("/*__EXT_APPS_BUNDLE__*/", () => bundleInline)
  .replace("__AMAZON_LOGO_LIGHT__", logoLight)
  .replace("__AMAZON_LOGO_DARK__", logoDark);

mkdirSync(join(root, "src", "generated"), { recursive: true });
writeFileSync(
  join(root, "src", "generated", "carousel-html.ts"),
  `// AUTO-GENERATED by scripts/build-widget.mjs — do not edit\n` +
    `export const CAROUSEL_HTML: string = ${JSON.stringify(html)};\n`,
);
console.log(`[build-widget] wrote src/generated/carousel-html.ts (${(html.length / 1024).toFixed(1)} KB)`);
